### ISSUE TITLE
Define our styleguide and update the eslint config to represent it

### ISSUE THREAD

**Issue by mauleb** [JBKLabs/eslint-config#3]
## Description

We will want thorough documentation of our style guide for numerous reasons. Using [airbnb](https://github.com/airbnb/javascript) as an example, define our styleguide within this repo.

## Implementation

* [ ] update the `README`
* [ ] update the eslint configuration to reflect the documented style guide

**Comment by mauleb** [comment]
I believe this issue can be closed for now @shvagen

**Comment by joshytaco** [comment]
Completed
